name: Auto-Approve

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: auto-approve-${{ github.event.pull_request.number }}

jobs:
  approve:
    name: Approve Owner PRs
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && github.event.pull_request.user.login == 'kkostov'
    steps:
      - name: Approve Pull Request
        env:
          GH_TOKEN: ${{ secrets.SAGA_SOFT_BOT_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr review "$PR_URL" --approve
